spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        handleRun-in-0:
          binder: rabbit
          destination: run-task
        handleRun-out-0:
          binder: rabbit
          destination: task-status-updated
