spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  cloud:
    stream:
      default:
        binder: rabbit
        group: fake-runner
      bindings:
        handleRun-in-0:
          destination: run-task
        handleRun-out-0:
          destination: task-status-updated
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
